import { useEffect, useMemo, useState } from 'react';
import ProductCard from '../components/ProductCard';
import { getProducts } from '../services/api';
import { filterProducts } from '../utils/catalog';
export default function Catalogo({ favorites, onToggleFavorite }){
 const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [category,setCategory]=useState('');
 useEffect(()=>{let active=true; getProducts().then(data=>{if(active)setProducts(data)}).catch(()=>{if(active)setError('Não foi possível carregar os produtos. Tente novamente em instantes.')}).finally(()=>{if(active)setLoading(false)}); return ()=>{active=false}},[]);
 const categories=useMemo(()=>[...new Set(products.map(p=>p.category))],[products]); const filtered=useMemo(()=>filterProducts(products,search,category),[products,search,category]);
 return <section className="section"><div className="section__head"><span className="section__eyebrow">Catálogo</span><h2>Explore os produtos</h2><p>Confira nossa seleção completa. Use a busca ou filtre por categoria para encontrar o que procura.</p></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome..." aria-label="Buscar produtos"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filtrar categoria"><option value="">Todas as categorias</option>{categories.map(item=><option key={item} value={item}>{item}</option>)}</select></div>{loading&&<div className="status">Carregando produtos...</div>}{error&&<div className="status status--error">{error}</div>}{!loading&&!error&&<div className="product-grid">{filtered.map(product=><ProductCard key={product.id} product={product} isFavorite={favorites.includes(product.id)} onToggleFavorite={onToggleFavorite}/>)}</div>}{!loading&&!error&&filtered.length===0&&<div className="status">Nenhum produto encontrado.</div>}</section>}
